// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptDealReducer from "../accept_deal_reducer";
import CastBallotReducer from "../cast_ballot_reducer";
import ClaimRoleReducer from "../claim_role_reducer";
import CounterDealReducer from "../counter_deal_reducer";
import EndorseCandidateReducer from "../endorse_candidate_reducer";
import ExposeDealReducer from "../expose_deal_reducer";
import ForceAdvanceReducer from "../force_advance_reducer";
import JoinGameReducer from "../join_game_reducer";
import ProposeDealReducer from "../propose_deal_reducer";
import ReactToCandidateReducer from "../react_to_candidate_reducer";
import RejectDealReducer from "../reject_deal_reducer";
import ResetMatchReducer from "../reset_match_reducer";
import SetPrioritiesReducer from "../set_priorities_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartMatchReducer from "../start_match_reducer";
import SubmitAllocationReducer from "../submit_allocation_reducer";
import SubmitChoiceReducer from "../submit_choice_reducer";
import WithdrawMyEndorsementReducer from "../withdraw_my_endorsement_reducer";

export type AcceptDealParams = __Infer<typeof AcceptDealReducer>;
export type CastBallotParams = __Infer<typeof CastBallotReducer>;
export type ClaimRoleParams = __Infer<typeof ClaimRoleReducer>;
export type CounterDealParams = __Infer<typeof CounterDealReducer>;
export type EndorseCandidateParams = __Infer<typeof EndorseCandidateReducer>;
export type ExposeDealParams = __Infer<typeof ExposeDealReducer>;
export type ForceAdvanceParams = __Infer<typeof ForceAdvanceReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type ProposeDealParams = __Infer<typeof ProposeDealReducer>;
export type ReactToCandidateParams = __Infer<typeof ReactToCandidateReducer>;
export type RejectDealParams = __Infer<typeof RejectDealReducer>;
export type ResetMatchParams = __Infer<typeof ResetMatchReducer>;
export type SetPrioritiesParams = __Infer<typeof SetPrioritiesReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type SubmitAllocationParams = __Infer<typeof SubmitAllocationReducer>;
export type SubmitChoiceParams = __Infer<typeof SubmitChoiceReducer>;
export type WithdrawMyEndorsementParams = __Infer<typeof WithdrawMyEndorsementReducer>;

