// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  phase: __t.string(),
  phaseEndsAt: __t.timestamp().name("phase_ends_at"),
  eventId: __t.string().name("event_id"),
  winnerRole: __t.string().name("winner_role"),
  flagship: __t.string(),
  sportsBudget: __t.u32().name("sports_budget"),
  cultureBudget: __t.u32().name("culture_budget"),
  hostelBudget: __t.u32().name("hostel_budget"),
  placementBudget: __t.u32().name("placement_budget"),
  welfareBudget: __t.u32().name("welfare_budget"),
  ballotsRevealed: __t.u32().name("ballots_revealed"),
  dealsLocked: __t.bool().name("deals_locked"),
  winAt: __t.u32().name("win_at"),
  ending: __t.string(),
  deadlineMicros: __t.u64().name("deadline_micros"),
});
