// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Ballot = __t.object("Ballot", {
  brokerRole: __t.string(),
  candidateRole: __t.string(),
});
export type Ballot = __Infer<typeof Ballot>;

export const BrokerResult = __t.object("BrokerResult", {
  brokerRole: __t.string(),
  score: __t.i32(),
  tier: __t.string(),
  dealHonoured: __t.bool(),
  hadDeal: __t.bool(),
  votedWinner: __t.bool(),
  minMet: __t.bool(),
  secretMet: __t.bool(),
  redLineHit: __t.bool(),
  endorsementBetrayal: __t.bool(),
});
export type BrokerResult = __Infer<typeof BrokerResult>;

export const CampusFact = __t.object("CampusFact", {
  id: __t.u64(),
  factId: __t.string(),
  sourceRole: __t.string(),
});
export type CampusFact = __Infer<typeof CampusFact>;

export const CandidateProfile = __t.object("CandidateProfile", {
  role: __t.string(),
  priorityOne: __t.string(),
  priorityTwo: __t.string(),
});
export type CandidateProfile = __Infer<typeof CandidateProfile>;

export const Deal = __t.object("Deal", {
  id: __t.u64(),
  candidateRole: __t.string(),
  brokerRole: __t.string(),
  promisedBudget: __t.u32(),
  promisedProject: __t.string(),
  requestedSupport: __t.string(),
  status: __t.string(),
  fromRole: __t.string(),
  exposed: __t.bool(),
});
export type Deal = __Infer<typeof Deal>;

export const Endorsement = __t.object("Endorsement", {
  brokerRole: __t.string(),
  candidateRole: __t.string(),
});
export type Endorsement = __Infer<typeof Endorsement>;

export const ExposedDeal = __t.object("ExposedDeal", {
  id: __t.u64(),
  candidateRole: __t.string(),
  brokerRole: __t.string(),
  promisedBudget: __t.u32(),
  promisedProject: __t.string(),
  requestedSupport: __t.string(),
});
export type ExposedDeal = __Infer<typeof ExposedDeal>;

export const FeedItem = __t.object("FeedItem", {
  id: __t.u64(),
  createdAt: __t.timestamp(),
  body: __t.string(),
});
export type FeedItem = __Infer<typeof FeedItem>;

export const HiddenChoice = __t.object("HiddenChoice", {
  id: __t.u64(),
  eventId: __t.string(),
  candidateRole: __t.string(),
  optionIndex: __t.u8(),
  budgetCommit: __t.u32(),
});
export type HiddenChoice = __Infer<typeof HiddenChoice>;

export const MatchState = __t.object("MatchState", {
  id: __t.u64(),
  phase: __t.string(),
  phaseEndsAt: __t.timestamp(),
  eventId: __t.string(),
  winnerRole: __t.string(),
  flagship: __t.string(),
  sportsBudget: __t.u32(),
  cultureBudget: __t.u32(),
  hostelBudget: __t.u32(),
  placementBudget: __t.u32(),
  welfareBudget: __t.u32(),
  ballotsRevealed: __t.u32(),
  dealsLocked: __t.bool(),
  winAt: __t.u32(),
  ending: __t.string(),
  deadlineMicros: __t.u64(),
  eventStage: __t.string(),
  stageDeadlineMicros: __t.u64(),
  choicesLocked: __t.u32(),
  reactionsLocked: __t.u32(),
});
export type MatchState = __Infer<typeof MatchState>;

export const MyBallot = __t.object("MyBallot", {});
export type MyBallot = __Infer<typeof MyBallot>;

export const MyDeal = __t.object("MyDeal", {});
export type MyDeal = __Infer<typeof MyDeal>;

export const MyHiddenChoice = __t.object("MyHiddenChoice", {});
export type MyHiddenChoice = __Infer<typeof MyHiddenChoice>;

export const MyRelationship = __t.object("MyRelationship", {});
export type MyRelationship = __Infer<typeof MyRelationship>;

export const PhaseTimer = __t.object("PhaseTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  kind: __t.string(),
});
export type PhaseTimer = __Infer<typeof PhaseTimer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  ready: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Reaction = __t.object("Reaction", {
  id: __t.u64(),
  eventId: __t.string(),
  brokerRole: __t.string(),
  candidateRole: __t.string(),
  stance: __t.string(),
});
export type Reaction = __Infer<typeof Reaction>;

export const Relationship = __t.object("Relationship", {
  id: __t.u64(),
  candidateRole: __t.string(),
  brokerRole: __t.string(),
  state: __t.string(),
});
export type Relationship = __Infer<typeof Relationship>;

export const RevealedBallot = __t.object("RevealedBallot", {
  brokerRole: __t.string(),
  candidateRole: __t.string(),
  matchedEndorsement: __t.bool(),
});
export type RevealedBallot = __Infer<typeof RevealedBallot>;

export const RevealedChoice = __t.object("RevealedChoice", {
  id: __t.u64(),
  eventId: __t.string(),
  candidateRole: __t.string(),
  optionIndex: __t.u8(),
  budgetCommit: __t.u32(),
});
export type RevealedChoice = __Infer<typeof RevealedChoice>;

